// <auto-generated />
using System;
using System.Collections.Generic;
using KinGraph.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KinGraph.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20260401005647_create_persons_table")]
    partial class create_persons_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("BloodType")
                        .HasColumnType("integer")
                        .HasColumnName("blood_type");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text")
                        .HasColumnName("marital_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<List<string>>("_languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("_languages");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DateOfBirth", "KinGraph.Core.Aggregates.PersonAggregate.Person.DateOfBirth#DateOfBirth", b1 =>
                        {
                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_of_birth_value");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmailAddress", "KinGraph.Core.Aggregates.PersonAggregate.Person.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_address_value");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Height", "KinGraph.Core.Aggregates.PersonAggregate.Person.Height#Height", b1 =>
                        {
                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("height_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("height_value");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Occupation", "KinGraph.Core.Aggregates.PersonAggregate.Person.Occupation#Occupation", b1 =>
                        {
                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("occupation_name");

                            b1.Property<decimal>("Salary")
                                .HasColumnType("numeric")
                                .HasColumnName("occupation_salary");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "KinGraph.Core.Aggregates.PersonAggregate.Person.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Extension")
                                .HasColumnType("text")
                                .HasColumnName("phone_number_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number_number");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PlaceOfBirth", "KinGraph.Core.Aggregates.PersonAggregate.Person.PlaceOfBirth#Address", b1 =>
                        {
                            b1.Property<int>("Country")
                                .HasColumnType("integer")
                                .HasColumnName("country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "City", "KinGraph.Core.Aggregates.PersonAggregate.Person.PlaceOfBirth#Address.City#City", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("place_of_birth_city_name");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "State", "KinGraph.Core.Aggregates.PersonAggregate.Person.PlaceOfBirth#Address.State#State", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("place_of_birth_state_name");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Weight", "KinGraph.Core.Aggregates.PersonAggregate.Person.Weight#Weight", b1 =>
                        {
                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("weight_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("weight_value");
                        });

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("RelatedPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("related_person_id");

                    b.Property<int>("source_person_id")
                        .HasColumnType("integer")
                        .HasColumnName("source_person_id");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_person_relationships");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_relationships_person_id");

                    b.HasIndex("source_person_id", "RelatedPersonId", "type")
                        .IsUnique()
                        .HasDatabaseName("ix_person_relationships_source_person_id_related_person_id_type");

                    b.ToTable("person_relationships", (string)null);

                    b.HasDiscriminator<string>("type").IsComplete(true).HasValue("Relationship");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.FamilyRelationship", b =>
                {
                    b.HasBaseType("KinGraph.Core.Aggregates.PersonAggregate.Relationship");

                    b.Property<int>("Degree")
                        .HasColumnType("integer")
                        .HasColumnName("degree");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<int>("GenerationOffset")
                        .HasColumnType("integer")
                        .HasColumnName("generation_offset");

                    b.Property<bool>("IsByMarriage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_by_marriage");

                    b.Property<bool>("IsHalf")
                        .HasColumnType("boolean")
                        .HasColumnName("is_half");

                    b.ToTable("person_relationships", (string)null);

                    b.HasDiscriminator().HasValue("relationship_family");
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.FriendRelationship", b =>
                {
                    b.HasBaseType("KinGraph.Core.Aggregates.PersonAggregate.Relationship");

                    b.ToTable("person_relationships", (string)null);

                    b.HasDiscriminator().HasValue("relationship_friend");
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.Person", b =>
                {
                    b.OwnsMany("KinGraph.Core.ValueObjects.Address", "Addresses", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Country")
                                .HasColumnType("integer")
                                .HasColumnName("country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.Property<int>("person_id")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.HasKey("id")
                                .HasName("pk_person_addresses");

                            b1.HasIndex("person_id")
                                .HasDatabaseName("ix_person_addresses_person_id");

                            b1.ToTable("person_addresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("person_id")
                                .HasConstraintName("fk_person_addresses_persons_person_id");

                            b1.OwnsOne("KinGraph.Core.ValueObjects.City", "City", b2 =>
                                {
                                    b2.Property<int>("Addressid")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("city_name");

                                    b2.HasKey("Addressid");

                                    b2.ToTable("person_addresses");

                                    b2.WithOwner()
                                        .HasForeignKey("Addressid")
                                        .HasConstraintName("fk_person_addresses_person_addresses_id");
                                });

                            b1.OwnsOne("KinGraph.Core.ValueObjects.State", "State", b2 =>
                                {
                                    b2.Property<int>("Addressid")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("state_name");

                                    b2.HasKey("Addressid");

                                    b2.ToTable("person_addresses");

                                    b2.WithOwner()
                                        .HasForeignKey("Addressid")
                                        .HasConstraintName("fk_person_addresses_person_addresses_id");
                                });

                            b1.Navigation("City")
                                .IsRequired();

                            b1.Navigation("State")
                                .IsRequired();
                        });

                    b.OwnsMany("KinGraph.Core.ValueObjects.Citizenship", "Citizenships", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<DateTime?>("AcquiredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("acquired_at");

                            b1.Property<int>("Country")
                                .HasColumnType("integer")
                                .HasColumnName("country");

                            b1.Property<int>("person_id")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.HasKey("id")
                                .HasName("pk_person_citizenships");

                            b1.HasIndex("person_id")
                                .HasDatabaseName("ix_person_citizenships_person_id");

                            b1.ToTable("person_citizenships", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("person_id")
                                .HasConstraintName("fk_person_citizenships_persons_person_id");
                        });

                    b.OwnsMany("KinGraph.Core.ValueObjects.ExtraField", "ExtraFields", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("value");

                            b1.Property<int>("person_id")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.HasKey("id")
                                .HasName("pk_person_extra_fields");

                            b1.HasIndex("person_id")
                                .HasDatabaseName("ix_person_extra_fields_person_id");

                            b1.ToTable("person_extra_fields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("person_id")
                                .HasConstraintName("fk_person_extra_fields_persons_person_id");
                        });

                    b.OwnsMany("KinGraph.Core.ValueObjects.GovermentalDocument", "GovernmentalDocuments", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<DateTime?>("ExpirationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expiration_date");

                            b1.Property<int?>("IssuingCountry")
                                .HasColumnType("integer")
                                .HasColumnName("issuing_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.Property<int>("person_id")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.HasKey("id")
                                .HasName("pk_person_documents");

                            b1.HasIndex("person_id")
                                .HasDatabaseName("ix_person_documents_person_id");

                            b1.ToTable("person_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("person_id")
                                .HasConstraintName("fk_person_documents_persons_person_id");
                        });

                    b.OwnsMany("KinGraph.Core.ValueObjects.Hobby", "Hobbies", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("person_id")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.HasKey("id")
                                .HasName("pk_person_hobbies");

                            b1.HasIndex("person_id")
                                .HasDatabaseName("ix_person_hobbies_person_id");

                            b1.ToTable("person_hobbies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("person_id")
                                .HasConstraintName("fk_person_hobbies_persons_person_id");
                        });

                    b.OwnsMany("KinGraph.Core.ValueObjects.SocialProfile", "SocialMediaProfiles", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Platform")
                                .HasColumnType("integer")
                                .HasColumnName("platform");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("username");

                            b1.Property<int>("person_id")
                                .HasColumnType("integer")
                                .HasColumnName("person_id");

                            b1.HasKey("id")
                                .HasName("pk_person_social_profiles");

                            b1.HasIndex("person_id")
                                .HasDatabaseName("ix_person_social_profiles_person_id");

                            b1.ToTable("person_social_profiles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("person_id")
                                .HasConstraintName("fk_person_social_profiles_persons_person_id");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Citizenships");

                    b.Navigation("ExtraFields");

                    b.Navigation("GovernmentalDocuments");

                    b.Navigation("Hobbies");

                    b.Navigation("SocialMediaProfiles");
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.Relationship", b =>
                {
                    b.HasOne("KinGraph.Core.Aggregates.PersonAggregate.Person", null)
                        .WithMany("Relationships")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("fk_person_relationships_persons_person_id");

                    b.HasOne("KinGraph.Core.Aggregates.PersonAggregate.Person", null)
                        .WithMany()
                        .HasForeignKey("source_person_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_relationships_persons_source_person_id");
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsOne("KinGraph.Core.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Extension")
                                .HasColumnType("text")
                                .HasColumnName("phone_number_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number_number");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("KinGraph.Core.Aggregates.PersonAggregate.Person", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
