global using System.ComponentModel.DataAnnotations;
global using Ardalis.Result;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using FluentValidation;
global using KinGraph.SharedKernel;
global using KinGraph.UseCases;
global using Mediator;
global using Microsoft.AspNetCore.Http.HttpResults;
